### PR TITLE
Use Buffer.from() instead of new Buffer(); require node >= 5.10.0.

### PR DESCRIPTION
**Pull request by millette**

### CODE REVIEW

**Comment by millette** [comment]
Weird failure on travis about yarn on event-stream dep:

> An unexpected error occurred: "http://localhost:4873/event-stream/-/event-stream-3.3.4.tgz: connect ECONNREFUSED 127.0.0.1:4873".

Same in #5.

**Comment by millette** [comment]
Seeing travis tests on node >= 8, perhaps I should change the node engine requirement to 8 also. I just went with the lower version to accomodate `Buffer.from(string)`.

**Comment by sergioramos** [comment]
this is great, thank you 🙏

**Comment by sergioramos** [comment]
also, added you as collaborator and will publish a major upgrade (might be a breaking change)

**Comment by millette** [comment]
Thanks!

**Pull request merged**
